
type = "service_account"
project_id = "tiketapp-462002"
private_key_id = "ec583e9f9b95f7897f6ad180c52abf23bee45f67"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCiX+oZgoUGK13k
eSJoQ9V5+zTUQzxr8TLBOnKaxpEq8iLmQhI0ax4ewudYjGkiouZMGR4pW5e+E9qR
T/dXy40sVP96SAQEcF9qdeEWEGPlaBPHxRWkGOr44K+Um25kRsPQy24QJlRFb7Z4
YOiO8tKl+u0SbhTVdj0UtNbU3ko6bzHhRxDLhRXI4Q4ql2M+4sjNeI056MAaXFNH
sS4jFbBpaJl6fYoDfDVNZM/PdhMmMMj6wWb+wJraI5BJ3aIp6RSC6uG06Ts9uqXy
076sEvNULDwSMLgj99dvgje1fwbxe3tUosagHlJeXUi3SSSsC9YRJbmaHoHIY6Fr
HCvKomKnAgMBAAECggEAK852qPU2kEiI50frCXgrkuI8CXwuQ+zpxYnQO4OQzKZQ
1hBDOxMfKCtrIM+Y2bhbK3KnWX8VfDl9ATEyyOPorWotFr9xHgV3KJCu7jXzzYN7
uqyoPwJd+lEb7ZrVeIZC9AS+J+s/VxBhiS6T72UBgbgl15ANXN2ucvSq9PkXy5Wf
ntJUOsBigh1KrFhYHjWfbv4EG3tw/3Vy932MbxUPMgnh81MfphlqvOqEwldBDL+e
6xZf2bbq+w69SMLFXQi1+D9+pp9jVdi0u9cv/n7m8xoG0Hfr1W1a1fKiw4oiMlCN
VjqJv/e6G5PvblccEhrDdTDDqxdzU8zml5mHTdrOoQKBgQDij1JgeOW3pwsIn4vx
DbTC8/6JX6MVWYMDHvN+BcJZ3AZvR/6B3+nRUHlCEuV45XIgwtB/PWztCtlXBJix
kX6qRsE5SCGjqK3wtyVklezcESTJDkLvaCu+JJOqrtLrKL7RgF2HIaCcih4rUn0l
uYO/goakGDpzhmzEyi4HHAMw8QKBgQC3eW0ByzyW5XoKcTbYy6TBHBKbGwrcj9iY
9aND5AaU9F7DMSJWugyb0D/PhBF8wm+xx10txgHDH3aU9SvylPCPqdGORkPziKe5
aNsqjqDognnCwex6BYy069BLWPxiB2P062UdwEpWnKlnWPlsqi7vEvRhetaDDf8b
7DubOqjNFwKBgE4Rowo5Prc9KXEsQTWsSmiPWVuPCAxYTuvpY3A+nc0HI3R/M3Uf
alvFRjN9fXNeZShi2SOvT/SSs3fnzpIJl8MnJHgPof/aJS34fjsd6oOeqLVbY7dJ
hyE7S2MaYPXFkZNxj0j8TnMCqQi2oQc52OtKGAk9jA64+IwLOzcZ8QORAoGBAIHo
XPFvOJhTJQUtwjrgfegpe1cNX7RpuWAcVJxmYO6o1Ev6hyjHFNRiMDw7c7JVbYZ/
9Y7Ka0cACRNRQOvC302pXPIS+Fv//1n9T2kjkfTvJU1rx4diVI1phpNDD3hNaU3q
Oi9Fjp0i0aOWUQzKtu6aCiTXN/mVOHNJ4a54azrDAoGBAKz67ZJKUgTVa7jVH8iS
JzjDLEfk3KdKtDxdYqRb7eUSQ7zUOHVqRVz7UnTjxm5DGXbkIvhXm1YnKxDbaicw
VbVhVT/uGG9d8I1rPz296JIRaa4ByRCNC1wUq/jeOch3BbgNu0Fp0wvwBYk1DkzN
4aDx1JuecGibqrjn2X0UhNBt
-----END PRIVATE KEY-----"""
client_email = "tiketapp-service-account@tiketapp-462002.iam.gserviceaccount.com"
client_id = "111460211734150197956"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tiketapp-service-account%40tiketapp-462002.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
